### ISSUE TITLE
Cert validity too long

### ISSUE THREAD

**Issue by Kevga** [FabulousCupcake/pcr-exporter#25]
The generated certificate has a validity period of 24 months. Using this on my Android 10 phone, I get ERR_CERT_VALIDITY_TOO_LONG. It seems the maximum validity period on Android has been reduced to 13 months about a year ago, see [this article](https://thehackernews.com/2020/09/ssl-tls-certificate-validity-398.html) for reference.

**Comment by FabulousCupcake** [comment]
Just saw this again — I thought it was a comment on the upstream repo 😂

I sent a pull-request months ago for this but doesn't seem like it will be merged (no response from maintainer):  
https://github.com/joeferner/node-http-mitm-proxy/pull/246

**Comment by FabulousCupcake** [comment]
I have an idea to improve the proxy part which will also fix this issue. It should be somewhere in the [projects](https://github.com/FabulousCupcake/pcr-exporter/projects/1) page.

Basically in addition to starting a simple proxy server, we also start a simple webserver (or just serve it on a specific endpoint) that serves a [PAC](https://en.wikipedia.org/wiki/Proxy_auto-config) file, which tells the device consuming the file to only direct requests to priconne-redive.us to the proxy server.

**Comment by Kevga** [comment]
Ah, I didn't think to check upstream. Another note on this, I looked up which validity period Charles proxy uses for its certificates, and it seems to set the issue date to 2000 and expiration to 2099. I guess if a certificate was issued before the restrictions on validity length were put in place, the certificate remains valid.

**Comment by FabulousCupcake** [comment]
https://github.com/joeferner/node-http-mitm-proxy/pull/246 finally got merged and I just updated `http-mitm-proxy` in #33.  
Finally can mark this as resolved 🙌
